name: Publish Packege

on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  SOLUTION_NAME: Bytegix.Lib.EventBus.sln
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'
  NUGET_SOURCE: 'https://api.nuget.org/v3/index.json'

jobs:
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/tests.template.yml
    with:
      dotnet_version: '$DOTNET_VERSION'
      configuration: $CONFIGURATION
      solution_name: $SOLUTION_NAME
      
  create_nuget:
    name: Create NuGet Package
    uses: ./.github/workflows/create-nuget.template.yml
    with:
      dotnet_version: '$DOTNET_VERSION'
      nuget_directory: nuget
      configuration: $CONFIGURATION
      solution_name: $SOLUTION_NAME

  publish_nuget:
    name: Publish NuGet Package
    uses: ./.github/workflows/publish-nuget.template.yml
    needs: [ create_nuget, run_tests ]
    with:
      dotnet_version: '$DOTNET_VERSION'
      nuget_source: $NUGET_SOURCE
      nuget_directory: nuget