name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

env:
  SOLUTION_NAME: Bytegix.Lib.EventBus.sln
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'

jobs:
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/tests.template.yml
    with:
      dotnet_version: ${{ env.DOTNET_VERSION }}
      configuration: ${{ env.CONFIGURATION }}
      solution_name: ${{ env.SOLUTION_NAME }}
      
  create_nuget:
    name: Create NuGet Package
    uses: ./.github/workflows/create-nuget.template.yml
    with:
      dotnet_version: $DOTNET_VERSION
      nuget_directory: nuget
      configuration: $CONFIGURATION
      solution_name: $SOLUTION_NAME